### ISSUE TITLE
Most important points

### ISSUE THREAD

**Issue by RobertKajnak** [KovaxG/Taskr#40]
@ramonabolboaca13 , @Alex-Barabasi , @KovaxG Please make  a not here what are the most important aspects in your work, or what you worked most hard on, that I should definately not forget to mention at the presentation

**Comment by ramonabolboaca13** [comment]
The entire project is important.I worked hard on everything. There are tests for input words using Regex, which was kind of new for me, how to check if an url image is a correct one, using txt files in the project, exporting and importing colors using txt files, the other aspects were pretty straightforward (making forms, loading a datagridview, processing data). If I remember somthing else I'll let you know.

**Comment by KovaxG** [comment]
I explored the wonderful new world of LINQ.

**Comment by RobertKajnak** [comment]
Please elaborate on LINQ

**Comment by RobertKajnak** [comment]
I meant aspects that you want me to bring up during presentation

**Comment by RobertKajnak** [comment]
@ramonabolboaca13 as such: why didn't you use regex for IsInjection method?

**Comment by KovaxG** [comment]
LINQ is somethink from functional programming incorporated into C#. By LINQ I mean those lambda taking methods, like FIND, WHERE, etc.

**Comment by Alex-Barabasi** [comment]
Learned how to use delegates, which I use extensively. Otherwise put a lot a work into every functionality. Debugged a lot, got really familiar with the Visual Studio programming environment and with Mysql Workbench. Created DatabaseHandler methods and used them for testing purposes. Used resharper. Besides this the obvious dynamical insertion of graphical objects.
